### ISSUE TITLE
sbt-blockade does not work with sbt-coursier (for transitive dependency violations?)

### ISSUE THREAD

**Issue by adelbertc** [Verizon/sbt-blockade#7]
It seems, at least from my experiments, that sbt-blockade does not play nice with [sbt-coursier](https://github.com/coursier/coursier) for transitive dependency violations. It seems to work fine for direct dependencies. Here is my reproduction:

### build.sbt
```scala
scalaVersion := "2.12.1"

blockadeUris := Seq(new java.net.URI(s"file:///${baseDirectory.in(ThisBuild).value}/blockade.json"))

compile in Compile := { blockade.value; (compile in Compile).value }

libraryDependencies += "co.fs2" %% "fs2-io" % "0.9.6"
```

### blockade.json
```json
{
  "blacklist": [
    {
      "organization": "co.fs2",
      "name": "fs2-core",
      "range": "(,0.9.6]",
      "expiry": "2017-09-21 00:00:00"
    }
  ]
}
```

### project/plugins.sbt
```scala
addSbtPlugin("io.verizon.build"  % "sbt-blockade" % "0.2.35")
// addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC3")
```

### project/build.properties
```
sbt.version=0.13.15
```

Running `blockade` warns as expected. Un-commenting the `sbt-coursier` plugin and running again says it succeeds.

If the `fs2-io` dependency is changed to `fs2-core` then it seems to succeed with or without Coursier :man_shrugging:

**Comment by timperrett** [comment]
@adelbertc i'm not sure what you're seeing here, but we use the two together without issue. If you collect more information then i'll happily reexamine this :-)

**Comment by adelbertc** [comment]
@timperrett The above is what I am seeing, those files are the reproduction. Without `sbt-coursier` blockade will warn, with it it passes.
